# Generated by Django 5.0.14 on 2025-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
    ]
