# Generated by Django 5.0.14 on 2025-11-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
